boostorg/variant

include/boost/variant/variant.hpp

because of the recent TypeTraits dependency drop in Move.
see https://github.com/boostorg/move/commit/8503b508e8028e5d433379c2963cc8d774214a5e

Add missing header in variant.hpp

---

include/boost/variant/detail/element_index.hpp
include/boost/variant/get.hpp

If `boost/variant/get.hpp` is included before other Variant headers the compiler can't find `boost::recursive_wrapper<>`.

Add missing headers in get.hpp and element_index.hpp

---

include/boost/variant/variant.hpp

This change reduces the number of Variant test failures from 23 to 6 when building with the Oracle compiler, and at least gets simple usage working.
I could also fix this by disabling conditional noexcept support in Config, but since it seems to be mostly working otherwise, that seems to be a shame.

Workaround for Oracle C++ compiler

---

include/boost/variant/recursive_wrapper_fwd.hpp

Add a missing include for mpl::true_/false_.
Compiling
```C++
#include <boost/variant/recursive_wrapper.hpp>
int main() { }
```
with GCC gives
```
In file included from boost_1_60_0/boost/variant/recursive_wrapper.hpp:16:0,
from test.cpp:1:
boost_1_60_0/boost/variant/recursive_wrapper_fwd.hpp:54:1: error: expected class-name before ‘{’ token
{
^
boost_1_60_0/boost/variant/recursive_wrapper_fwd.hpp:60:1: error: expected class-name before ‘{’ token
{
^
```

Missing include in recursive_wrapper_fwd.hpp.

---

doc/reference/get.xml
doc/reference/polymorphic_get.xml

I noticed some minor typos in the documentation of boost::variant and fixed them.

Typos in Documentation

---

include/boost/variant/detail/visitation_impl.hpp

This change suppress implicit instantiation of MPL end iterator in the code using `boost::make_variant_over` with some MPL sequence.
Some of the MPL iterators (for instance, boost::fusion::vector's iterator) can not be used as complete type.
Therefore, `make_variant_over` with such an iterator results in a compile error.
```cpp
#include <boost/fusion/container/vector.hpp>
#include <boost/fusion/mpl.hpp>
#include <boost/variant/variant.hpp>
int main()
{
boost::make_variant_over<boost::fusion::vector<int, char>>::type t{};
}
```
This change fix the issue by avoiding the template implicit instantiation due to ADL.

Suppress implicit instantiation of MPL end iterator

---

include/boost/variant/get.hpp
test/Jamfile.v2
test/variant_get_test.cpp
test/variant_rvalue_get_with_ampersand_test.cpp

This PR adds rvalue version of get<>().
Tests for expected behaviour and compile errors are added.
Ticket: https://svn.boost.org/trac/boost/ticket/13018.

Add rvalue get<>() support + tests.

---

include/boost/variant/variant.hpp
test/variant_over_joint_view_test.cpp

make_over_sequence works if use mpl::list instead of vector. Speeding up compilation using specification for mpl::vector<Args...> conflicts with old mpl::vector and does not work - so it was abandoned.

Fix joint view

---

include/boost/variant/variant.hpp

MSVC complained that this expression had no effect. Cast to void to
silence the warning.

Fix warning in warning suppression code

---

include/boost/variant/detail/apply_visitor_binary.hpp

For boost::is_lvalue_reference.

Add missing include in apply_visitor_binary.hpp

---

include/boost/variant/detail/apply_visitor_unary.hpp
test/const_ref_apply_visitor.cpp

Added apply_visitor with Visitor&&. Allows to bind Visitor&&, Visitor& and const Visitor&.
Removed apply_visitor with const Visitor& since it was catching inlined Visitors&&.
Passing const Visitor to result_wrapper resulted in compilation error when Visitor was mutable.
Fixes: https://github.com/boostorg/variant/issues/39

Perfect forwarding for passing visitor in apply_visitor.

---

test/test7.cpp
test/test8.cpp

When compiled with C++17 features enabled, class variant is defined in both namespace 'std' and namespace 'boost'.
Signed-off-by: Daniela Engert <dani@ngrt.de>

disambiguate class variant.

---

include/boost/variant/detail/apply_visitor_unary.hpp
test/Jamfile.v2
test/variant_visit_internal_linkage.cpp

This avoids using `boost::declval` inside evaluated contexts, which is invalid and will actually be diagnosed [by compilers][1] when the type used inside `boost::declval` has internal linkage (such as an anonymous namespace).
[1]: https://bugs.llvm.org/show_bug.cgi?id=35842

Rewrite the deduction of visitor return type

---

include/boost/variant/detail/apply_visitor_binary.hpp
include/boost/variant/detail/apply_visitor_unary.hpp

EDG 3.2 is pretty old (the workaround added 16 years ago).

Remove EDG 3.2 workaround

---

include/boost/variant/static_visitor.hpp

otherwise in C++ 17 mode Clang 8 will complain about the
protected destructor:
```
main.cpp:16:33: error: temporary of type 'boost::static_visitor<>' has protected destructor
boost::apply_visitor(output{}, v);
^
/usr/local/opt/boost/include/boost/variant/static_visitor.hpp:53:5: note: declared protected here
~static_visitor() = default;
^
```
See also discussion in https://reviews.llvm.org/D53860

static_visitor: Make destructor public

---

doc/design.xml
doc/reference/apply_visitor.xml
doc/reference/recursive_wrapper.xml
doc/reference/variant.xml
doc/tutorial/advanced.xml
include/boost/variant/recursive_wrapper.hpp
include/boost/variant/recursive_wrapper_fwd.hpp
include/boost/variant/variant.hpp
test/Jamfile.v2
test/recursive_wrapper_move_only_test.cpp

Instead of allocating a new object just steal the pointer from the other
recursive_wrapper. It is much cheaper and allows to mark the move constructor
noexcept (allows variant to move the object without backup copying it).
Fixes #58.

recursive_wrapper move constructor pointer stealing

---

include/boost/variant/detail/forced_return.hpp

Reduces code bloating on Clang and MSVC, saves a branch on GCC.
The noreturn warnings have also been tested on https://godbolt.org/z/T5gmlV
ref https://github.com/boostorg/variant/issues/60#issuecomment-476382413.

Do not call abort in forced_return

---

include/boost/variant/detail/apply_visitor_unary.hpp
test/const_ref_apply_visitor.cpp

Ensures that we can e.g. call apply_visitor on a lvalue variant
e.g. works up to 1.69, broken in 1.70 (broken by #55)
#include <boost/variant.hpp>
int main() {
boost::variant<int, long> v;
boost::apply_visitor([](auto& i) {}, v);
}

Copy variant cvref when determining result type

---

include/boost/variant/variant.hpp

A fix for my failing CI jobs, I use -Werror 
https://travis-ci.com/HDembinski/histogram/jobs/192785991

fix for unused argument warning

---

include/boost/variant/detail/visitation_impl.hpp
include/boost/variant/variant.hpp

Because a visitor is wrapped several times during visitation it cases extra temporaries usage and useless store and loads that can only be optimized if the `visitation_impl` is inlined into the function that creates the wrapper. Clang inliner decides not to inline functions even with small-sized switches, resulting in a poor visitation code. Forceinline mark on those internal functions perceptibly improves the situation, though does not mitigate it completely.
LLVM ticket https://bugs.llvm.org/show_bug.cgi?id=41491
Before:
```asm
foo:
sub	rsp, 88
lea	rax, [rsp + 64]
mov	qword ptr [rsp + 72], rax
lea	rax, [rsp + 72]
mov	qword ptr [rsp + 80], rax
mov	eax, dword ptr [rcx]
lea	r9, [rcx + 4]
mov	edx, eax
sar	edx, 31
xor	edx, eax
xorps	xmm0, xmm0
movups	xmmword ptr [rsp + 48], xmm0
lea	r8, [rsp …
```

Partly mitigate bad Clang inlining decision

---

include/boost/variant/detail/apply_visitor_binary.hpp
include/boost/variant/detail/move.hpp
test/recursive_wrapper_move_test.cpp

`-fsyntax-only` times for `#include <boost/variant.hpp>`
```
mingw    0.72 -> 0.56 (22%)
clang-cl 0.85 -> 0.70 (18%)
```

Remove unused includes

---

include/boost/variant/detail/apply_visitor_binary.hpp
include/boost/variant/detail/apply_visitor_unary.hpp
include/boost/variant/detail/multivisitors_cpp14_based.hpp
include/boost/variant/detail/visitation_impl.hpp
include/boost/variant/get.hpp
include/boost/variant/polymorphic_get.hpp
include/boost/variant/variant.hpp
test/variant_visit_test.cpp

Fixes GCC's zero-as-null-pointer-constat warnings.
Resolves issue #76

Fix GCC zero-as-null-pointer-constat warnings

---

include/boost/variant/variant.hpp

The warnings are generated by `no_exceptions_support.hpp`. While at it, this commit also updates locations of several other headers that were moved and don't generate warnings (yet).
Deprecated headers will be removed in a future release.

Update header locations to avoid warnings about using deprecated headers

---

include/boost/variant/bad_visit.hpp

Allow header file to be built standalone, in a clang C++ modules context.

Add missing include

---

include/boost/variant/detail/multivisitors_cpp14_based.hpp

This makes the header able to be built standalone, making possible C++ clang modules builds.
@vgvassilev

Added missing <tuple> include

---

include/boost/variant/variant.hpp

Workaround https://github.com/boostorg/variant/issues/97

clang/c++23: disable converting move assignment

---

include/boost/variant/recursive_wrapper.hpp

The later has been deprecated:
```cpp
// The header file at this path is deprecated;
// use boost/core/checked_delete.hpp instead.
```

refactor: use core/checked_delete over checked_delete

---

include/boost/variant/get.hpp
include/boost/variant/polymorphic_get.hpp

refactor: use core/addressof over utility/addressof

---

test/rvalue_test.cpp

This header is deprecated and will be removed. There is `boost/core/invoke_swap.hpp` as a replacement, but it isn't needed in this case.

Remove deprecated `boost/swap.hpp` include
